const T=[
['discount','Discount Calculator','🏷️','Savings','Find sale price and savings.',[['p','Original price','number'],['d','Discount %','number']],v=>`Sale price: ${M(v.p*(1-v.d/100))}<br>Savings: ${M(v.p*v.d/100)}`],
['tip','Tip Calculator','🍽️','Money','Calculate tip and total.',[['b','Bill amount','number'],['t','Tip %','number']],v=>`Tip: ${M(v.b*v.t/100)}<br>Total: ${M(v.b*(1+v.t/100))}`],
['percentage','Percentage Calculator','%','Money','Find a percentage of a number.',[['n','Number','number'],['p','Percent','number']],v=>`${v.p}% of ${v.n} = <b>${F(v.n*v.p/100)}</b>`],
['temperature','Temperature Converter','🌡️','Everyday','Convert Fahrenheit and Celsius.',[['v','Temperature','number'],['f','From','select:Fahrenheit|Celsius']],v=>v.f==='Fahrenheit'?`${F((v.v-32)*5/9)} °C`:`${F(v.v*9/5+32)} °F`],
['tax','Sales Tax Calculator','🧾','Money','Calculate tax and final price.',[['p','Price','number'],['t','Tax %','number']],v=>`Tax: ${M(v.p*v.t/100)}<br>Total: ${M(v.p*(1+v.t/100))}`],
['markup','Markup Calculator','📦','Business','Price an item using markup.',[['c','Cost','number'],['m','Markup %','number']],v=>`Markup: ${M(v.c*v.m/100)}<br>Selling price: ${M(v.c*(1+v.m/100))}`],
['age','Age Calculator','🎂','Everyday','Calculate age from a birth date.',[['b','Birth date','date'],['a','As of','date']],v=>{let b=new Date(v.b),a=new Date(v.a),x=a.getFullYear()-b.getFullYear();if(a.getMonth()<b.getMonth()||(a.getMonth()==b.getMonth()&&a.getDate()<b.getDate()))x--;return `Age: <b>${Math.max(0,x)} years</b>`}],
['days','Days Between Dates','📅','Everyday','Count days between two dates.',[['a','Start','date'],['b','End','date']],v=>`Days: <b>${Math.round(Math.abs(new Date(v.b)-new Date(v.a))/86400000)}</b>`],
['miles','Miles Converter','🛣️','Everyday','Convert miles and kilometers.',[['v','Distance','number'],['f','From','select:Miles|Kilometers']],v=>v.f==='Miles'?`${F(v.v*1.609344)} km`:`${F(v.v/1.609344)} miles`],
['pounds','Pounds Converter','⚖️','Everyday','Convert pounds and kilograms.',[['v','Weight','number'],['f','From','select:Pounds|Kilograms']],v=>v.f==='Pounds'?`${F(v.v*.45359237)} kg`:`${F(v.v/.45359237)} lb`],
['fraction','Fraction Calculator','➗','Money','Add, subtract, multiply or divide fractions.',[['a','First fraction','text'],['o','Operation','select:+|-|×|÷'],['b','Second fraction','text']],v=>FR(v.a,v.o,v.b)],
['loan','Loan Payment Calculator','💳','Money','Estimate monthly loan payments.',[['p','Loan amount','number'],['r','Annual interest %','number'],['y','Term in years','number']],v=>LOAN(v.p,v.r,v.y)],
['mortgage','Mortgage Calculator','🏠','Money','Estimate principal and interest payment.',[['p','Loan amount','number'],['r','Annual interest %','number'],['y','Term in years','number']],v=>LOAN(v.p,v.r,v.y)+'<p class="note">Estimate excludes taxes, insurance and HOA fees.</p>'],
['gas','Gas Mileage Calculator','⛽','Savings','Calculate MPG.',[['m','Miles driven','number'],['g','Gallons used','number']],v=>`Fuel economy: <b>${F(v.m/v.g)} MPG</b>`],
['paycheck','Paycheck Calculator','💵','Money','Estimate take-home pay.',[['g','Gross pay','number'],['d','Deductions %','number']],v=>`Estimated take-home: <b>${M(v.g*(1-v.d/100))}</b><p class="note">Simple estimate, not a tax calculation.</p>`],
['interest','Compound Interest Calculator','📈','Money','Estimate growth with compound interest.',[['p','Starting amount','number'],['r','Annual rate %','number'],['y','Years','number'],['c','Annual contribution','number']],v=>{let r=v.r/100;let fv=v.p*Math.pow(1+r,v.y)+v.c*((Math.pow(1+r,v.y)-1)/(r||1));return `Estimated value: <b>${M(fv)}</b>`}],
['ratio','Ratio Calculator','🔢','Business','Scale a ratio to a new quantity.',[['a','Ratio A','number'],['b','Ratio B','number'],['c','Known new value','number']],v=>`Other value: <b>${F(v.c*v.b/v.a)}</b>`],
['businessdays','Business Days Calculator','💼','Business','Count weekdays between dates.',[['a','Start','date'],['b','End','date']],v=>{let a=new Date(v.a),b=new Date(v.b);if(a>b)[a,b]=[b,a];let n=0;for(;a<=b;a.setDate(a.getDate()+1)){let d=a.getDay();if(d>0&&d<6)n++}return `Business days: <b>${n}</b>`}],
['kg','Kilograms ↔ Pounds','⚖️','Everyday','Convert kilograms and pounds.',[['v','Weight','number'],['f','From','select:Kilograms|Pounds']],v=>v.f==='Kilograms'?`${F(v.v*2.2046226)} lb`:`${F(v.v/2.2046226)} kg`],
['length','Feet/Inches ↔ Centimeters','📏','Everyday','Convert common length measurements.',[['v','Value','number'],['f','From','select:Feet|Inches|Centimeters']],v=>v.f==='Feet'?`${F(v.v*30.48)} cm`:v.f==='Inches'?`${F(v.v*2.54)} cm`:`${F(v.v/30.48)} ft / ${F(v.v/2.54)} in`]
];
const grid=document.querySelector('#grid'),modal=document.querySelector('#modal'),form=document.querySelector('#form'),res=document.querySelector('#result');const F=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2}),M=n=>Number(n).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
function render(q=''){grid.innerHTML='';T.filter(t=>(t[1]+' '+t[3]+' '+t[4]).toLowerCase().includes(q.toLowerCase())).forEach(t=>{let e=document.createElement('article');e.className='tool';e.innerHTML=`<div>${t[2]}</div><h3>${t[1]}</h3><p>${t[4]}</p>`;e.onclick=()=>openTool(t);grid.append(e)})}
function openTool(t){document.querySelector('#title').textContent=t[1];document.querySelector('#cat').textContent=t[3];res.hidden=true;form.innerHTML=t[5].map(f=>f[2].startsWith('select:')?`<div class="field"><label>${f[1]}</label><select id="x${f[0]}">${f[2].slice(7).split('|').map(o=>`<option>${o}</option>`).join('')}</select></div>`:`<div class="field"><label>${f[1]}</label><input id="x${f[0]}" type="${f[2]}" step="any"></div>`).join('')+'<button class="calc">Calculate</button><p class="note">Informational estimate only. Verify important financial decisions with a qualified professional.</p>';modal.hidden=false;form.querySelector('.calc').onclick=()=>{let v={};t[5].forEach(f=>v[f[0]]=f[2]==='number'?Number(document.querySelector('#x'+f[0]).value):document.querySelector('#x'+f[0]).value);try{res.innerHTML=t[6](v);res.hidden=false}catch(e){res.textContent='Please check your entries.';res.hidden=false}}}
function Q(s){let p=s.trim().split('/').map(Number);return[p[0],p[1]||1]}function FR(a,o,b){let x=Q(a),y=Q(b),n,d;if(o==='+'){n=x[0]*y[1]+y[0]*x[1];d=x[1]*y[1]}else if(o==='-'){n=x[0]*y[1]-y[0]*x[1];d=x[1]*y[1]}else if(o==='×'){n=x[0]*y[0];d=x[1]*y[1]}else{n=x[0]*y[1];d=x[1]*y[0]}return `Result: <b>${n}/${d}</b> (${F(n/d)})`}function LOAN(p,r,y){let m=r/100/12,n=y*12;if(!m)return `Monthly payment: <b>${M(p/n)}</b>`;let x=p*m/(1-Math.pow(1+m,-n));return `Estimated monthly payment: <b>${M(x)}</b><p class="note">Estimated total: ${M(x*n)}</p>`}
document.querySelector('#search').oninput=e=>render(e.target.value);document.querySelector('#close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};document.querySelector('#year').textContent=new Date().getFullYear();render();