const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),v=id=>Number(document.getElementById(id).value),out=(id,m)=>document.getElementById(id).textContent=m;
function discountCalc(){let p=v('price'),d=v('discount');if(p<0||d<0||d>100||!isFinite(p)||!isFinite(d))return out('discountResult','Enter a valid price and discount.');let s=p*d/100;out('discountResult',`You save ${money(s)} — sale price ${money(p-s)}.`)}
function tipCalc(){let b=v('bill'),t=v('tip');if(b<0||t<0||!isFinite(b)||!isFinite(t))return out('tipResult','Enter a valid bill and tip.');let x=b*t/100;out('tipResult',`Tip: ${money(x)} — Total: ${money(b+x)}.`)}
function percentCalc(){let p=v('part'),w=v('whole');if(!isFinite(p)||!isFinite(w)||w===0)return out('percentResult','Enter valid numbers; whole cannot be zero.');out('percentResult',`${(p/w*100).toFixed(2)}%`)}
function toC(){let f=v('temp');if(!isFinite(f))return out('tempResult','Enter a temperature.');out('tempResult',`${((f-32)*5/9).toFixed(1)} °C`)}function toF(){let c=v('temp');if(!isFinite(c))return out('tempResult','Enter a temperature.');out('tempResult',`${(c*9/5+32).toFixed(1)} °F`)}
function taxCalc(){let p=v('taxPrice'),r=v('taxRate');if(p<0||r<0||!isFinite(p)||!isFinite(r))return out('taxResult','Enter a valid price and tax rate.');let x=p*r/100;out('taxResult',`Tax: ${money(x)} — Total: ${money(p+x)}.`)}
function markupCalc(){let c=v('cost'),m=v('markup');if(c<0||m<0||!isFinite(c)||!isFinite(m))return out('markupResult','Enter a valid cost and markup.');let x=c*m/100;out('markupResult',`Markup: ${money(x)} — Selling price: ${money(c+x)}.`)}
function ageCalc(){let b=document.getElementById('birth').value;if(!b)return out('ageResult','Choose a birth date.');let d=new Date(b+'T00:00:00'),n=new Date(),a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;out('ageResult',a<0?'Enter a valid birth date.':`You are approximately ${a} years old.`)}
function daysCalc(){let a=document.getElementById('dateA').value,b=document.getElementById('dateB').value;if(!a||!b)return out('daysResult','Choose both dates.');let x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00'),d=Math.round(Math.abs(y-x)/86400000);out('daysResult',`${d} day${d===1?'':'s'} between the dates.`)}
function convertMiKm(){let n=v('distance');if(!isFinite(n))return out('distanceResult','Enter a distance.');out('distanceResult',`${n} mi = ${(n*1.609344).toFixed(3)} km`)}function convertKmMi(){let n=v('distance');if(!isFinite(n))return out('distanceResult','Enter a distance.');out('distanceResult',`${n} km = ${(n/1.609344).toFixed(3)} miles`)}
function convertLbKg(){let n=v('weight');if(!isFinite(n))return out('weightResult','Enter a weight.');out('weightResult',`${n} lb = ${(n*.45359237).toFixed(3)} kg`)}function convertKgLb(){let n=v('weight');if(!isFinite(n))return out('weightResult','Enter a weight.');out('weightResult',`${n} kg = ${(n/.45359237).toFixed(3)} lb`)}
